services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    container_name: mokart-web-prod
    ports:
      - "9980:80"
    restart: always
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: mokart-api-prod
    ports:
      - "9981:5000"
    volumes:
      - ./api:/app
    environment:
      - DATABASE_URL=postgresql://${DB_USER:-mokart}:${DB_PASSWORD:-mokart123}@192.168.112.2:5432/${DB_NAME:-mokart}
      - DB_HOST=db-prod
    depends_on:
      - db
    restart: always

  app:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    container_name: mokart-app-prod
    ports:
      - "9979:80"
    restart: always

  db:
    image: postgres:15-alpine
    container_name: mokart-db-prod
    environment:
      - POSTGRES_USER=${DB_USER:-mokart}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-mokart123}
      - POSTGRES_DB=${DB_NAME:-mokart}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
      - ./api/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./api/circuits.sql:/docker-entrypoint-initdb.d/02-circuits.sql
    restart: unless-stopped

volumes:
  postgres_data_prod:
