services:

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: mokart-app
    ports:
      - "8000:3000"
    volumes:
      - ./app/src:/app/src
      - ./app/public:/app/public
    environment:
      - REACT_API_URL=https://api.novationlabs.fr
    restart: unless-stopped

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: mokart-web
    ports:
      - "8080:3000"
    volumes:
      - ./web/src:/app/src
      - ./web/public:/app/public
    restart: unless-stopped

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: mokart-api
    ports:
      - "8081:5000"
    volumes:
      - ./api:/app
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    depends_on:
      - db
    restart: unless-stopped

  pgadmin:
      image: dpage/pgadmin4
      container_name: mokart-pgadmin
      environment:
        - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
        - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
      ports:
        - "5050:80"
      depends_on:
        - db
      restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: mokart-db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./api/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  postgres_data:
