name: Docker Build Dev

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env
        run: cp .env.example .env

      - name: Build Docker images
        run: docker compose build
